let userNickname = "Nataliia";
console.log(userNickname);
let userScore = 5;
console.log(userScore);
let age = 35;
console.log(age);
age += 5;
console.log(age);
let isStudent = true;
console.log(isStudent);
isStudent = false;
console.log(isStudent);
let item = 10;
console.log(item);
item = "ten";
console.log(item);
item = true;
console.log(item);